=== hro424/okl4-sh/tools/pyelf/dtd/memstats-2.0.dtd
<!--
  @LICENCE("Open Kernel Labs, Inc.", "2007")@

  DTD of the elfweaver memstats output spec file.
-->

<!ELEMENT memstats (revision?, environment, resources) >
<!ELEMENT revision EMPTY >

<!ELEMENT environment (kernel, cell+) >
<!ELEMENT kernel (id_range*, pool*, space) >
<!ELEMENT cell ((id_range | pool)*, space*) >

<!ELEMENT id_range EMPTY >
<!ELEMENT pool EMPTY >
<!ELEMENT space ((id_range | pool)*, program+, thread*, mutex*) >
<!ELEMENT program (psec_list, object_list?) >
<!ELEMENT psec_list (psec+) >
<!ELEMENT psec EMPTY >
<!ELEMENT object_list (object*) >
<!ELEMENT object EMPTY >
<!ELEMENT thread EMPTY >
<!ELEMENT mutex EMPTY >

<!ELEMENT resources (phys_mem?, section_list, segment_list, sas_list, ids, pools) >
<!ELEMENT phys_mem (section*) >
<!ELEMENT section_list (section*) >
<!ELEMENT section EMPTY >
<!ELEMENT segment_list (segment+) >
<!ELEMENT segment EMPTY >
<!ELEMENT sas_list (sas+) >
<!ELEMENT sas EMPTY >
<!ELEMENT ids (id_pool*) >
<!ELEMENT id_pool (range*) >
<!ELEMENT range EMPTY >
<!ELEMENT pools ((virt_mem | mem_pool)*) >
<!ELEMENT virt_mem (vm_section*) >
<!ELEMENT vm_section EMPTY >
<!ELEMENT mem_pool (group*) >
<!ELEMENT group EMPTY >

<!-- Attributes -->

<!ATTLIST revision repository CDATA #IMPLIED >
<!ATTLIST revision changeset  CDATA #IMPLIED >

<!-- Attributes within the envorinment section -->
<!ATTLIST environment type CDATA #IMPLIED >

<!ATTLIST cell name CDATA #IMPLIED >

<!ATTLIST id_range name CDATA #REQUIRED >
<!ATTLIST id_range node IDREF #REQUIRED >

<!ATTLIST pool id   ID    #REQUIRED >
<!ATTLIST pool vmid IDREF #REQUIRED >

<!ATTLIST space name CDATA #REQUIRED >

<!ATTLIST program name CDATA #REQUIRED >

<!ATTLIST psec name   CDATA #REQUIRED >
<!ATTLIST psec phys   IDREF #REQUIRED >
<!ATTLIST psec virt   IDREF #REQUIRED >

<!ATTLIST object_list num_text CDATA #REQUIRED >
<!ATTLIST object_list num_data CDATA #REQUIRED >

<!ATTLIST object type (text | data) #REQUIRED >
<!ATTLIST object name CDATA         #REQUIRED >
<!ATTLIST object size CDATA         #REQUIRED >


<!ATTLIST thread pool_id   IDREF #REQUIRED >
<!ATTLIST thread handle_id IDREF #REQUIRED >
<!ATTLIST thread clist_id  IDREF #REQUIRED >

<!ATTLIST mutex pool_id   IDREF #REQUIRED >
<!ATTLIST mutex clist_id  IDREF #REQUIRED >

<!-- Attributes within the resources section -->
<!ATTLIST phys_mem machine CDATA #REQUIRED >
<!ATTLIST phys_mem name    CDATA #REQUIRED >
<!ATTLIST phys_mem pool    CDATA #REQUIRED >

<!ATTLIST section id   ID    #REQUIRED >
<!ATTLIST section address CDATA       #REQUIRED >
<!ATTLIST section size  CDATA       #REQUIRED >

<!ATTLIST segment sections IDREFS         #REQUIRED >
<!ATTLIST segment phys     CDATA          #REQUIRED >
<!ATTLIST segment virt     CDATA          #REQUIRED >
<!ATTLIST segment filesz   CDATA          #REQUIRED >
<!ATTLIST segment memsz    CDATA          #REQUIRED >

<!ATTLIST sas id  ID #REQUIRED >

<!ATTLIST id_pool name   CDATA #REQUIRED >
<!ATTLIST id_pool parent IDREF #IMPLIED >
<!ATTLIST id_pool source IDREF #REQUIRED >
<!ATTLIST id_pool total  CDATA #REQUIRED >

<!ATTLIST range id    ID    #REQUIRED >
<!ATTLIST range start CDATA #REQUIRED >
<!ATTLIST range size  CDATA #REQUIRED >

<!ATTLIST virt_mem id     ID    #REQUIRED >
<!ATTLIST virt_mem sas_id IDREF #REQUIRED >

<!ATTLIST vm_section id      ID #REQUIRED >
<!ATTLIST vm_section address CDATA #REQUIRED >
<!ATTLIST vm_section size    CDATA #REQUIRED >

<!ATTLIST mem_pool id         ID #REQUIRED >
<!ATTLIST mem_pool node       IDREF #REQUIRED >
<!ATTLIST mem_pool block_size CDATA #IMPLIED>

<!ATTLIST group name CDATA            #REQUIRED >
<!ATTLIST group type (normal | small) #IMPLIED >
<!ATTLIST group size CDATA            #REQUIRED >

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/memstats_simple.xml
<?xml version="1.0"?>
<!DOCTYPE memstats SYSTEM "memstats-2.0.dtd">
<memstats>
  <revision  repository="ssh://hg.ok-labs.com//hg/okl4-mainline"  changeset="12345678+ tip" />
  <environment type="Nano">
    <kernel>
      <pool id="kheap" vmid="phys8" />
      <space name="kspace">
        <pool id="vm0" vmid="kspc" />
        <program name="kernel">
          <psec_list>
            <psec name="kernel.vectors" phys="phys0" virt="kspc0" />
            <psec name="kernel.asmtext" phys="phys1" virt="kspc1" />
            <psec name="kernel.data" phys="phys2" virt="kspc2" />
            <psec name="kernel.bss" phys="phys3" virt="kspc3" />
            <psec name="kernel.text" phys="phys4" virt="kspc4" />
            <psec name="kernel.init" phys="phys5" virt="kspc5" />
            <psec name="kernel.stack" phys="phys6" virt="kspc6" />
            <psec name="kernel.user_helpers" phys="phys7" virt="kspc7" />
            <psec name="kernel.heap" phys="phys8" virt="kspc8" />
            <psec name="(weaved object)" phys="phys9" virt="kspc9" />
            <psec name="(weaved object)" phys="phys15" virt="kspc10" />
            <psec name="(weaved object)" phys="phys16" virt="kspc11" />
            <psec name="(weaved object)" phys="phys17" virt="kspc12" />
            <psec name="(weaved object)" phys="phys18" virt="kspc13" />
            <psec name="(weaved object)" phys="phys19" virt="kspc14" />
            <psec name="(weaved object)" phys="phys14" virt="kspc15" />
            <psec name="(weaved object)" phys="phys11" virt="kspc16" />
            <psec name="(weaved object)" phys="phys20" virt="kspc17" />
            <psec name="(weaved object)" phys="phys21" virt="kspc18" />
            <psec name="(weaved object)" phys="phys0" virt="kspc19" />
            <psec name="(weaved object)" phys="phys18" virt="kspc20" />
            <psec name="(weaved object)" phys="phys22" virt="kspc21" />
            <psec name="(weaved object)" phys="phys7" virt="kspc22" />
          </psec_list>
          <object_list num_text="45" num_data="21">
            <object type="text" name="hash_tag" size="56"/>
            <object type="text" name="copy_message" size="52"/>
            <object type="text" name="thread_reap" size="92"/>
            <object type="text" name="sys_ipc_send" size="24"/>
            <object type="text" name="putchar" size="48"/>
            <object type="text" name="yield" size="112"/>
            <object type="text" name="sys_interrupt_pre_thread_delete_callback" size="60"/>
            <object type="text" name="sys_interrupt_register" size="112"/>
            <object type="text" name="sys_yield" size="12"/>
            <object type="text" name="plat_mask_interrupt" size="32"/>
            <object type="text" name="__assert_failure" size="16"/>
            <object type="text" name="sys_futex_wait" size="284"/>
            <object type="text" name="plat_decode_interrupt" size="28"/>
            <object type="text" name="sys_signal_post_thread_delete_callback" size="4"/>
            <object type="text" name="deactivate_self_schedule" size="84"/>
            <object type="text" name="puts" size="52"/>
            <object type="text" name="sys_signal_poll" size="48"/>
            <object type="text" name="plat_unmask_interrupt" size="32"/>
            <object type="text" name="sys_thread_create" size="216"/>
            <object type="text" name="sys_ipc_recv" size="280"/>
            <object type="text" name="sys_ipc_send_c" size="412"/>
            <object type="text" name="sys_ipc_post_thread_delete_callback" size="4"/>
            <object type="text" name="schedule" size="12"/>
            <object type="text" name="sys_ipc_post_thread_create_callback" size="4"/>
            <object type="text" name="deactivate_self" size="76"/>
            <object type="text" name="activate" size="60"/>
            <object type="text" name="arch_enable_interrupt" size="4"/>
            <object type="text" name="vprintk" size="360"/>
            <object type="text" name="sys_futex_signal" size="300"/>
            <object type="text" name="printk" size="32"/>
            <object type="text" name="sys_signal_wait" size="64"/>
            <object type="text" name="sys_interrupt_wait" size="68"/>
            <object type="text" name="c_handle_interrupt" size="88"/>
            <object type="text" name="arch_disable_interrupt" size="4"/>
            <object type="text" name="sys_interrupt_deregister" size="108"/>
            <object type="text" name="sys_thread_myself" size="28"/>
            <object type="text" name="sys_ipc_pre_thread_delete_callback" size="4"/>
            <object type="text" name="sys_signal_post_thread_create_callback" size="4"/>
            <object type="text" name="plat_putc" size="36"/>
            <object type="text" name="sys_signal_pre_thread_create_callback" size="16"/>
            <object type="text" name="sys_thread_join" size="176"/>
            <object type="text" name="sys_signal_pre_thread_delete_callback" size="4"/>
            <object type="text" name="sys_signal_send" size="172"/>
            <object type="text" name="sys_thread_exit" size="120"/>
            <object type="text" name="sys_ipc_pre_thread_create_callback" size="4"/>
            <object type="data" name="futex_hash_slots" size="4"/>
            <object type="data" name="kernel_api_version" size="4"/>
            <object type="data" name="futex_hash" size="4"/>
            <object type="data" name="futex_pending_tags" size="4"/>
            <object type="data" name="tcbs" size="4"/>
            <object type="data" name="serial_mem0" size="4"/>
            <object type="data" name="interrupt_mem0" size="4"/>
            <object type="data" name="priority_heads" size="4"/>
            <object type="data" name="max_tcbs" size="4"/>
            <object type="data" name="priority_bitmap" size="4"/>
            <object type="data" name="tcb_free_head" size="4"/>
            <object type="data" name="futex_hash_slots_lg2" size="4"/>
            <object type="data" name="output_lock" size="0"/>
            <object type="data" name="num_pending_tags" size="4"/>
            <object type="data" name="futex_lock" size="0"/>
            <object type="data" name="ipc_lock" size="0"/>
            <object type="data" name="signal_lock" size="0"/>
            <object type="data" name="tcb_lock" size="0"/>
            <object type="data" name="schedule_lock" size="0"/>
            <object type="data" name="interrupt_handlers" size="128"/>
            <object type="data" name="interrupt_lock" size="0"/>
          </object_list>
        </program>
      </space>
    </kernel>
    <cell name="ntest">
      <space name="">
        <pool id="vm1" vmid="kspc" />
        <program name="nanotest">
          <psec_list>
            <psec name="nanotest.text" phys="phys9" virt="kspc9" />
            <psec name="nanotest.data" phys="phys11" virt="kspc16" />
          </psec_list>
          <object_list num_text="207" num_data="174">
            <object type="text" name="nanotest-test_ATOMIC_1000_func" size="304"/>
            <object type="text" name="nanotest-test1000_child_thread" size="76"/>
            <object type="text" name="nanotest-test_FUTEX_1200_func" size="244"/>
            <object type="text" name="nanotest-test_FUTEX_1110_func" size="376"/>
            <object type="text" name="nanotest-test_FUTEX_1100_func" size="212"/>
            <object type="text" name="nanotest-test_FUTEX_1011_func" size="120"/>
            <object type="text" name="nanotest-test_FUTEX_1010_func" size="68"/>
            <object type="text" name="nanotest-test_FUTEX_1000_func" size="160"/>
            <object type="text" name="nanotest-futex1100_child" size="112"/>
            <object type="text" name="nanotest-futex1110_child" size="152"/>
            <object type="text" name="nanotest-futex1200_child" size="80"/>
            <object type="text" name="nanotest-test_INT_1100_func" size="128"/>
            <object type="text" name="nanotest-test_INT_1003_func" size="260"/>
            <object type="text" name="nanotest-test_INT_1002_func" size="204"/>
            <object type="text" name="nanotest-test_INT_1001_func" size="208"/>
            <object type="text" name="nanotest-test_INT_1000_func" size="116"/>
            <object type="text" name="nanotest-int1002_child" size="100"/>
            <object type="text" name="nanotest-int1003_child" size="52"/>
            <object type="text" name="nanotest-int1100_child" size="52"/>
            <object type="text" name="nanotest-test_IPC_2010_func" size="96"/>
            <object type="text" name="nanotest-test_IPC_2000_func" size="104"/>
            <object type="text" name="nanotest-test_IPC_1020_func" size="180"/>
            <object type="text" name="nanotest-test_IPC_1010_func" size="72"/>
            <object type="text" name="nanotest-test_IPC_1000_func" size="72"/>
            <object type="text" name="nanotest-send_null_ipc" size="52"/>
            <object type="text" name="nanotest-recv_null_ipc" size="176"/>
            <object type="text" name="nanotest-ipc1020_sender" size="8"/>
            <object type="text" name="nanotest-test2000_child" size="60"/>
            <object type="text" name="nanotest-test2010_child" size="72"/>
            <object type="text" name="nanotest-__PERF_TEST_FUNC__PERF_FUTEX2010" size="4"/>
            <object type="text" name="nanotest-futex2010" size="212"/>
            <object type="text" name="nanotest-__PERF_TEST_FUNC__PERF_FUTEX2000" size="4"/>
            <object type="text" name="nanotest-futex2000" size="204"/>
            <object type="text" name="nanotest-__PERF_TEST_FUNC__PERF_FUTEX1210" size="4"/>
            <object type="text" name="nanotest-futex1210_preemptee" size="32"/>
            <object type="text" name="nanotest-futex1210_main" size="108"/>
            <object type="text" name="nanotest-futex1210_helper" size="112"/>
