=== hro424/okl4-sh/tools/pyelf/dtd/weaver-2.0.dtd
<!--
  @LICENCE("Open Kernel Labs, Inc.", "2007, 2008")@

  DTD of the elfweaver spec file.

  Author: Malcolm Purvis <malcolmp@ok-labs.com>
-->

<!ELEMENT image (machine, (virtual_pool|physical_pool)*, kernel, (iguana)*, (okl4)*)>
<!ELEMENT machine ((cpu|page_size+|word_size|kernel_heap_attrs|cache_policy+|phys_device|virtual_memory+|physical_memory+)*)>
<!ELEMENT page_size EMPTY >
<!ELEMENT word_size EMPTY >
<!ELEMENT cache_policy EMPTY >
<!ELEMENT kernel_heap_attrs EMPTY >
<!ELEMENT virtual_memory (region+) >
<!ELEMENT physical_memory (region+) >
<!ELEMENT region EMPTY >
<!ELEMENT phys_device ((physical_memory|interrupt)*) >
<!ELEMENT interrupt EMPTY >
<!ELEMENT kernel ((segment*|patch*|heap?|config?|dynamic?|use_device*)*) >
<!ELEMENT segment (cap)* >
<!ELEMENT patch EMPTY >
<!ELEMENT config (option+) >
<!ELEMENT option EMPTY >
<!ELEMENT dynamic EMPTY >
<!ELEMENT virtual_pool (memory+) >
<!ELEMENT physical_pool (memory+) >
<!ELEMENT memory EMPTY >
<!ELEMENT iguana ((segment*|patch*|extension*|environment?|pd|program)*) >
<!ELEMENT extension ((segment*|patch*)*) >
<!ELEMENT program (stack?|heap?|commandline?|memsection*|environment?|segment*|patch*|thread*|zone*|virt_device*)+ >
<!ELEMENT pd (memsection*|environment?|segment*|patch*|thread*|zone*)+ >
<!ELEMENT zone ((memsection|segment)+) >
<!ELEMENT stack (cap)* >
<!ELEMENT heap (cap)* >
<!ELEMENT memsection (cap)* >
<!ELEMENT cap (right)+ >
<!ELEMENT right EMPTY >
<!ELEMENT virt_device EMPTY >
<!ELEMENT thread (stack?|commandline?)* >
<!ELEMENT commandline (arg)* >
<!ELEMENT arg EMPTY >
<!ELEMENT environment (entry)* >
<!ELEMENT entry EMPTY >
<!ELEMENT cpu EMPTY >
<!ELEMENT okl4 ((patch*|memsection*|commandline?|stack*|heap*|segment*|space*|irq*|environment*|mutex*|thread*|use_device*)*) >
<!ELEMENT use_device EMPTY >
<!ELEMENT mutex EMPTY >
<!ELEMENT irq EMPTY >
<!ELEMENT space ((mutex*|thread*|memsection*|irq*)*) >


<!ATTLIST image xmlns CDATA #IMPLIED >

<!ATTLIST machine file CDATA #IMPLIED >

<!ATTLIST word_size size CDATA #REQUIRED >
<!ATTLIST page_size size CDATA #REQUIRED >
<!ATTLIST kernel_heap_attrs distance CDATA #IMPLIED >
<!ATTLIST kernel_heap_attrs align CDATA #IMPLIED >

<!ATTLIST cache_policy name CDATA #REQUIRED >
<!ATTLIST cache_policy value CDATA #REQUIRED >

<!ATTLIST virtual_memory name CDATA #REQUIRED >

<!ATTLIST physical_memory name CDATA #REQUIRED >

<!ATTLIST region base CDATA #REQUIRED >
<!ATTLIST region size CDATA #REQUIRED >
<!ATTLIST region type CDATA #IMPLIED >
<!ATTLIST region rights CDATA #IMPLIED >
<!ATTLIST region cache_policy CDATA #IMPLIED >

<!ATTLIST phys_device name CDATA #REQUIRED >

<!ATTLIST virt_device name CDATA #REQUIRED >

<!ATTLIST interrupt name CDATA #REQUIRED >
<!ATTLIST interrupt number CDATA #REQUIRED >

<!ATTLIST kernel file CDATA #REQUIRED >
<!ATTLIST kernel xip (true|false) #IMPLIED >
<!ATTLIST kernel physpool CDATA #REQUIRED >
<!ATTLIST kernel virtpool CDATA #REQUIRED >

<!ATTLIST segment name      CDATA #REQUIRED >
<!ATTLIST segment phys_addr CDATA #IMPLIED >
<!ATTLIST segment physpool  CDATA #IMPLIED >
<!ATTLIST segment align     CDATA #IMPLIED >
<!ATTLIST segment attach    (r|w|x|rw|rx|wx|rwx) #IMPLIED >
<!ATTLIST segment pager     CDATA #IMPLIED >
<!ATTLIST segment direct    (true|false) #IMPLIED >
<!ATTLIST segment protected (true|false) #IMPLIED >
<!ATTLIST segment cache_policy CDATA #IMPLIED >

<!ATTLIST patch address CDATA #REQUIRED >
<!ATTLIST patch value CDATA #REQUIRED >
<!ATTLIST patch bytes CDATA #IMPLIED >

<!ATTLIST stack size      CDATA #IMPLIED >
<!ATTLIST stack virt_addr CDATA #IMPLIED >
<!ATTLIST stack phys_addr CDATA #IMPLIED >
<!ATTLIST stack physpool  CDATA #IMPLIED >
<!ATTLIST stack virtpool  CDATA #IMPLIED >
<!ATTLIST stack align     CDATA #IMPLIED >
<!ATTLIST stack attach    (r|w|x|rw|rx|wx|rwx) #IMPLIED >
<!ATTLIST stack pager     CDATA #IMPLIED >
<!ATTLIST stack direct    (true|false) #IMPLIED >
<!ATTLIST stack zero      (true|false) #IMPLIED >
<!ATTLIST stack cache_policy CDATA #IMPLIED >

<!ATTLIST heap size      CDATA #IMPLIED >
<!ATTLIST heap virt_addr CDATA #IMPLIED >
<!ATTLIST heap phys_addr CDATA #IMPLIED >
<!ATTLIST heap physpool  CDATA #IMPLIED >
<!ATTLIST heap virtpool  CDATA #IMPLIED >
<!ATTLIST heap align     CDATA #IMPLIED >
<!ATTLIST heap attach    (r|w|x|rw|rx|wx|rwx) #IMPLIED >
<!ATTLIST heap pager     CDATA #IMPLIED >
<!ATTLIST heap direct    (true|false) #IMPLIED >
<!ATTLIST heap zero      (true|false) #IMPLIED >
<!ATTLIST heap cache_policy CDATA #IMPLIED >
<!ATTLIST heap user_map  (true|false) #IMPLIED >

<!ATTLIST option key   CDATA #REQUIRED >
<!ATTLIST option value CDATA #REQUIRED >

<!ATTLIST dynamic align CDATA #IMPLIED >
<!ATTLIST dynamic max_threads CDATA #IMPLIED >

<!ATTLIST extension name     CDATA #REQUIRED >
<!ATTLIST extension file     CDATA #IMPLIED >
<!ATTLIST extension start    CDATA #IMPLIED >
<!ATTLIST extension physpool CDATA #IMPLIED >
<!ATTLIST extension pager    CDATA #IMPLIED >
<!ATTLIST extension direct   (true|false) #IMPLIED >

<!ATTLIST virtual_pool name CDATA #REQUIRED >

<!ATTLIST physical_pool name CDATA #REQUIRED >
<!ATTLIST physical_pool direct (true|false) #IMPLIED >

<!ATTLIST memory src  CDATA #IMPLIED >
<!ATTLIST memory base CDATA #IMPLIED >
<!ATTLIST memory size CDATA #IMPLIED >

<!ATTLIST iguana name     CDATA #REQUIRED >
<!ATTLIST iguana file     CDATA #REQUIRED >
<!ATTLIST iguana physpool CDATA #IMPLIED >
<!ATTLIST iguana virtpool CDATA #IMPLIED >
<!ATTLIST iguana pager    CDATA #IMPLIED >
<!ATTLIST iguana direct   (true|false) #IMPLIED >
<!ATTLIST iguana kernel_heap CDATA #REQUIRED >
<!ATTLIST iguana caps     CDATA #IMPLIED >
<!ATTLIST iguana clists   CDATA #IMPLIED >
<!ATTLIST iguana spaces   CDATA #IMPLIED >
<!ATTLIST iguana mutexes  CDATA #IMPLIED >
<!ATTLIST iguana threads  CDATA #IMPLIED >
<!ATTLIST iguana priority CDATA #IMPLIED >
<!ATTLIST iguana platform_control CDATA #IMPLIED >

<!ATTLIST zone name CDATA #REQUIRED >
<!ATTLIST zone physpool CDATA #IMPLIED >
<!ATTLIST zone virtpool CDATA #IMPLIED >

<!ATTLIST program name     CDATA #REQUIRED >
<!ATTLIST program file     CDATA #REQUIRED >
<!ATTLIST program priority CDATA #IMPLIED >
<!ATTLIST program physpool CDATA #IMPLIED >
<!ATTLIST program virtpool CDATA #IMPLIED >
<!ATTLIST program pager    CDATA #IMPLIED >
<!ATTLIST program direct   (true|false) #IMPLIED >
<!ATTLIST program server   CDATA #IMPLIED >
<!ATTLIST program platfrom_control (true|false) #IMPLIED >

<!ATTLIST pd name     CDATA #REQUIRED >
<!ATTLIST pd file     CDATA #IMPLIED >
<!ATTLIST pd physpool CDATA #IMPLIED >
<!ATTLIST pd virtpool CDATA #IMPLIED >
<!ATTLIST pd pager    CDATA #IMPLIED >
<!ATTLIST pd direct   (true|false) #IMPLIED >
<!ATTLIST pd platfrom_control (true|false) #IMPLIED >

<!ATTLIST memsection name      CDATA #REQUIRED >
<!ATTLIST memsection file      CDATA #IMPLIED >
<!ATTLIST memsection size      CDATA #IMPLIED >
<!ATTLIST memsection direct    (true|false) #IMPLIED >
<!ATTLIST memsection virt_addr CDATA #IMPLIED >
<!ATTLIST memsection phys_addr CDATA #IMPLIED >
<!ATTLIST memsection physpool  CDATA #IMPLIED >
<!ATTLIST memsection virtpool  CDATA #IMPLIED >
<!ATTLIST memsection align     CDATA #IMPLIED >
<!ATTLIST memsection attach    (r|w|x|rw|rx|wx|rwx) #IMPLIED >
<!ATTLIST memsection pager     CDATA #IMPLIED >
<!ATTLIST memsection zero      (true|false) #IMPLIED >
<!ATTLIST memsection cache_policy CDATA #IMPLIED >
<!ATTLIST memsection mem_type  CDATA #IMPLIED >

<!ATTLIST cap name CDATA #REQUIRED >

<!ATTLIST right value CDATA #REQUIRED >

<!ATTLIST thread name     CDATA #REQUIRED >
<!ATTLIST thread start    CDATA #REQUIRED >
<!ATTLIST thread priority CDATA #IMPLIED >
<!ATTLIST thread physpool CDATA #IMPLIED >
<!ATTLIST thread virtpool CDATA #IMPLIED >

<!ATTLIST arg value CDATA #REQUIRED >

<!ATTLIST entry key    CDATA #REQUIRED >
<!ATTLIST entry value  CDATA #IMPLIED >
<!ATTLIST entry cap    CDATA #IMPLIED >
<!ATTLIST entry attach CDATA #IMPLIED >

<!ATTLIST cpu name CDATA #REQUIRED >

<!ATTLIST okl4 name CDATA #REQUIRED >
<!ATTLIST okl4 file CDATA #REQUIRED >
<!ATTLIST okl4 physpool CDATA #IMPLIED >
<!ATTLIST okl4 virtpool CDATA #IMPLIED >
<!ATTLIST okl4 pager CDATA #IMPLIED >
<!ATTLIST okl4 direct (true|false) #IMPLIED >
<!ATTLIST okl4 kernel_heap CDATA #REQUIRED >
<!ATTLIST okl4 caps CDATA #IMPLIED >
<!ATTLIST okl4 clists CDATA #IMPLIED >
<!ATTLIST okl4 spaces CDATA #IMPLIED >
<!ATTLIST okl4 mutexes CDATA #IMPLIED >
<!ATTLIST okl4 threads CDATA #IMPLIED >
<!ATTLIST okl4 priority CDATA #IMPLIED >
<!ATTLIST okl4 platform_control CDATA #IMPLIED >

<!ATTLIST space name CDATA #REQUIRED >
<!ATTLIST space physpool CDATA #IMPLIED >
<!ATTLIST space virtpool CDATA #IMPLIED >
<!ATTLIST space pager CDATA #IMPLIED >
<!ATTLIST space direct (true|false) #IMPLIED >

<!ATTLIST irq value CDATA #REQUIRED >

<!ATTLIST mutex name CDATA #REQUIRED >

<!ATTLIST use_device name CDATA #REQUIRED >

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/nano_simple_cell.xml
<?xml version="1.0" ?>
<!DOCTYPE image
  SYSTEM 'weaver-2.0.dtd'>
<image>
	<machine>
		<cpu name="xscale"/>
		<word_size size="0x20"/>
		<virtual_memory name="virtual">
			<region base="0x80000000" size="0x50000000"/>
		</virtual_memory>
		<physical_memory name="sdram">
			<region base="0x5c000000" rights="all" size="0x40000"/>
		</physical_memory>
		<physical_memory name="rom">
			<region base="0xa3800000" rights="all" size="0x800000"/>
		</physical_memory>
		<physical_memory name="physical">
			<region base="0xa0000000" rights="all" size="0x3800000"/>
		</physical_memory>
		<physical_memory name="pcmcia_cf_slot_1">
			<region base="0x30000000" rights="all" size="0x10000000"/>
		</physical_memory>
		<physical_memory name="pcmcia_cf_slot_0">
			<region base="0x20000000" rights="all" size="0x10000000"/>
		</physical_memory>
		<phys_device name="test_dev">
			<interrupt name="int_test0" number="1"/>
			<interrupt name="int_test1" number="3"/>
		</phys_device>
		<phys_device name="timer_dev">
			<physical_memory name="timer_mem0">
				<region base="0x40a00000" cache_policy="uncached" rights="all" size="0x1000"/>
			</physical_memory>
			<interrupt name="int_timer0" number="27"/>
			<interrupt name="int_timer1" number="28"/>
		</phys_device>
		<phys_device name="serial_dev">
			<physical_memory name="serial_mem0">
				<region base="0x40100000" cache_policy="uncached" rights="all" size="0x1000"/>
			</physical_memory>
			<interrupt name="int_serial0" number="22"/>
		</phys_device>
		<phys_device name="rtc_dev">
			<physical_memory name="rtc_mem0">
				<region base="0x40900000" cache_policy="uncached" rights="all" size="0x1000"/>
			</physical_memory>
			<interrupt name="int_rtc0" number="31"/>
		</phys_device>
		<page_size size="0x1000"/>
		<page_size size="0x10000"/>
		<page_size size="0x100000"/>
	</machine>
	<physical_pool direct="true" name="sdram">
		<memory src="sdram"/>
	</physical_pool>
	<physical_pool direct="true" name="rom">
		<memory src="rom"/>
	</physical_pool>
	<virtual_pool name="virtual">
		<memory src="virtual"/>
	</virtual_pool>
	<physical_pool direct="true" name="physical">
		<memory src="physical"/>
	</physical_pool>
	<physical_pool direct="true" name="pcmcia_cf_slot_1">
		<memory src="pcmcia_cf_slot_1"/>
	</physical_pool>
	<physical_pool direct="true" name="pcmcia_cf_slot_0">
		<memory src="pcmcia_cf_slot_0"/>
	</physical_pool>
    <kernel file="data/eg_weave/nanokernel" physpool="physical" virtpool="virtual">
		<heap align="0x4000"/>
	</kernel>
    <okl4 file="data/eg_weave/nano_hello" kernel_heap="0x200000" name="nano_hello">
		<heap size="0x100000"/>
	</okl4>
</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/multiple_pager.xml
<?xml version="1.0"?>
<!DOCTYPE image SYSTEM "weaver-2.0.dtd">
<image>
	<machine file="data/eg_weave/machine.xml" />
	<virtual_pool name="virtual">
		<memory base="0x1000" size="0xcffff000"/>
	</virtual_pool>

	<physical_pool name="physical">
		<memory base="0xa0000000" size="0x3800000"/>
	</physical_pool>

	<kernel file="data/eg_weave/l4kernel" virtpool="virtual" physpool="physical">
	</kernel>

	<iguana name="iguana_server" file="data/eg_weave/ig_server" kernel_heap="2M">
	        <!-- Load all segments with a custom pager. -->
        	<program name="ig_naming" file="data/eg_weave/ig_naming" pager="memload">
		</program>
	</iguana>
</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/scatter_load.xml
<?xml version="1.0"?>
<!DOCTYPE image SYSTEM "weaver-2.0.dtd">
<image>
	<machine file="data/eg_weave/machine.xml">
	</machine>
	<virtual_pool name="virtual">
		<memory base="0x1000" size="0xcffff000"/>
	</virtual_pool>

	<physical_pool name="physical">
		<memory base="0xa0000000" size="0x3800000"/>
	</physical_pool>

	<kernel file="data/eg_weave/l4kernel" virtpool="virtual" physpool="physical">
	</kernel>

	<iguana name="iguana_server" file="data/eg_weave/ig_server" kernel_heap="2M">
	        <program name="scatter_load" file="data/arm_scatter_load">
		</program>
	</iguana>
</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/multiple_device_regions.xml
<?xml version="1.0"?>
<!DOCTYPE image SYSTEM "weaver-2.0.dtd">
<image>
    <machine>
        <cpu name="xscale" />
		<word_size size="0x20" />
		<virtual_memory name="virtual">
			<region base="0x1000" size="0xcffff000" />
		</virtual_memory>
		<physical_memory name="physical">
			<region base="0xa0000000" size="0x3800000" />
		</physical_memory>
		<page_size size="0x1000" />

        <phys_device name="dummy_dev">
            <physical_memory name="dummy_mem0">
                <region base="0x40100000" size="0x1000" />
            </physical_memory>
            <physical_memory name="dummy_mem1">
                <region base="0x40102000" size="0x3000" />
            </physical_memory>
            <interrupt name="int_dummy0" number="10" />
        </phys_device>

	</machine>

	<virtual_pool name="virtual">
		<memory base="0x1000" size="0xcffff000"/>
	</virtual_pool>

	<physical_pool name="physical">
		<memory base="0xa0000000" size="0x3800000"/>
	</physical_pool>

	<kernel file="data/eg_weave/l4kernel" virtpool="virtual" physpool="physical">
	</kernel>

	<iguana name="iguana_server" file="data/eg_weave/ig_server" kernel_heap="2M">
        <program name="ig_naming" file="data/eg_weave/ig_naming">
		</program>
	</iguana>
</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/ignore_program_test.xml
<?xml version="1.0"?>
<!DOCTYPE image SYSTEM "weaver-2.0.dtd">
<image>
	<machine>
		<cpu name="xscale" />
		<word_size size="0x20" />
		<virtual_memory name="virtual">
			<region base="0x1000" size="0xcffff000" />
		</virtual_memory>
		<physical_memory name="physical">
			<region base="0xa0000000" size="0x3800000" />
		</physical_memory>
		<page_size size="0x1000" />
	</machine>

	<virtual_pool name="virtual">
		<memory base="0x1000" size="0xcffff000"/>
	</virtual_pool>

	<physical_pool name="physical">
		<memory base="0xa0000000" size="0x3800000"/>
	</physical_pool>

	<kernel file="data/eg_weave/l4kernel" virtpool="virtual" physpool="physical">
	</kernel>

	<iguana name="iguana_server" file="data/eg_weave/ig_server" kernel_heap="2M">
		<program name="ig_naming" priority="200" file="data/eg_weave/ig_naming" >
		</program>
		<program name="ig_serial" priority="-1" file="data/eg_weave/ig_serial" >
		</program>
		<program name="ig_timer" priority="240"	file="data/eg_weave/ig_timer" >
		</program>
		<program name="vmlinux" priority="-1" file="data/eg_weave/vmlinux" >
		</program>
	</iguana>
</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/okl4_cell.xml
<?xml version="1.0" ?>
<!DOCTYPE image
  SYSTEM 'weaver-2.0.dtd'>
<image>
	<machine>
		<cpu name="xscale"/>
		<word_size size="0x20"/>
		<virtual_memory name="virtual">
			<region base="0x80000000" size="0x50000000"/>
		</virtual_memory>
		<physical_memory name="sdram">
			<region base="0x5c000000" size="0x40000" rights="all"/>
		</physical_memory>
		<physical_memory name="rom">
			<region base="0xa3800000" size="0x800000"/>
		</physical_memory>
		<physical_memory name="physical">
			<region base="0xa0000000" size="0x3800000"/>
		</physical_memory>
		<physical_memory name="pcmcia_cf_slot_1">
			<region base="0x30000000" size="0x10000000"/>
		</physical_memory>
		<physical_memory name="pcmcia_cf_slot_0">
			<region base="0x20000000" size="0x10000000"/>
		</physical_memory>
		<phys_device name="timer_dev">
			<physical_memory name="timer_mem0">
				<region base="0x40a00000" size="0x1000"/>
			</physical_memory>
			<interrupt name="int_timer0" number="27"/>
			<interrupt name="int_timer1" number="28"/>
		</phys_device>
		<phys_device name="serial_dev">
			<physical_memory name="serial_mem0">
                <region base="0x40100000" size="0x1000" cache_policy="uncached"/>
                <region base="0x40101000" size="0x1000"/>
                <region base="0x40102000" size="0x1000"/>
            </physical_memory>
            <physical_memory name="serial_mem1">
                <region base="0x40103000" size="0x1000"/>
            </physical_memory>
			<interrupt name="int_serial0" number="22"/>
		</phys_device>
		<phys_device name="rtc_dev">
			<physical_memory name="rtc_mem0">
				<region base="0x40900000" size="0x1000"/>
			</physical_memory>
			<interrupt name="int_rtc0" number="31"/>
		</phys_device>
		<page_size size="0x1000"/>
		<page_size size="0x10000"/>
		<page_size size="0x100000"/>
	</machine>
	<physical_pool direct="true" name="sdram">
		<memory src="sdram"/>
	</physical_pool>
	<physical_pool direct="true" name="rom">
		<memory src="rom"/>
	</physical_pool>
	<virtual_pool name="virtual">
		<memory src="virtual"/>
	</virtual_pool>
	<physical_pool direct="true" name="physical">
		<memory src="physical"/>
	</physical_pool>
	<physical_pool direct="true" name="pcmcia_cf_slot_1">
		<memory src="pcmcia_cf_slot_1"/>
	</physical_pool>
	<physical_pool direct="true" name="pcmcia_cf_slot_0">
		<memory src="pcmcia_cf_slot_0"/>
	</physical_pool>
    <kernel file="data/eg_weave/l4kernel" physpool="physical" virtpool="virtual">
		<config>
			<option key="threads" value="1024"/>
		</config>
	</kernel>
    <okl4 priority="100" clists="256" file="data/eg_weave/first_cell" kernel_heap="0x200000" mutexes="256" name="ktest" spaces="251" platform_control="True">
        <mutex name="cell_mutex"/>
        <environment>
            <entry key="test_key" value="42"/>
            <entry key="my_mutex" cap="test_space/test_space_mutex1" />
            <entry key="my_memory" cap="normal" />
            <entry key="my_memory_phys" cap="normal/physical" />
            <entry key="my_heap_phys" cap="heap/physical" />
            <entry key="some_text" cap="rx" />
            <entry key="some_data" cap="rw" attach="rw" />
            <entry key="my_memory2" cap="test_space/normal2" />
            <entry key="other_thread" cap="/second_cell/main" />
        </environment>
		<memsection cache_policy="uncached" name="serial_vaddr" phys_addr="0x40100000" size="0x1000" />
        <memsection mem_type="unmapped" name="ktest_segment" size="0x4000" />
        <memsection name="normal" size="0x4000" />
        <space name="test_space">
            <mutex name="test_space_mutex1"/>
            <mutex name="test_space_mutex2"/>
            <memsection name="normal2" size="0x4000" />
        </space>
        <space name="thread_space">
            <thread name="test_thread" start="_entry"/>
        </space>
        <irq value="825"/>
        <heap size="0x100000"/>
        <thread name="second_main_thread" start="_start"/>
        <use_device name="serial_dev"/>
        <commandline>
            <arg value="ktest"/>
            <arg value="42"/>
            <arg value="arg with space"/>
        </commandline>
	</okl4>
        <okl4 clists="0" file="data/eg_weave/second_cell" kernel_heap="0x200000" mutexes="0" name="second_cell" spaces="5">
            <heap size="0x100000"/>
            <environment>
              <entry key="test_mutex" cap="/ktest/test_space/test_space_mutex1"/>
            <entry key="their_memory" cap="/ktest/normal" />
        </environment>
        </okl4>

</image>

=== hro424/okl4-sh/tools/pyelf/tests/data/eg_weave/environment.xml
<?xml version="1.0"?>
<!DOCTYPE image SYSTEM "weaver-2.0.dtd">
<image>
	<machine file="data/eg_weave/machine.xml">
	</machine>
	<virtual_pool name="virtual">
		<memory base="0x1000" size="0xcffff000"/>
	</virtual_pool>

	<physical_pool name="large">
		<memory base="0xa0000000" size="0x3000000"/>
	</physical_pool>

	<physical_pool name="physical">
		<memory base="0xa3000000" size="0x1000000"/>
	</physical_pool>

	<kernel file="data/eg_weave/l4kernel" virtpool="virtual" physpool="physical">
	</kernel>

	<iguana name="iguana_server" file="data/eg_weave/ig_server" kernel_heap="2M">
		<pd name="the_pd" >
			<memsection name="make_dynamically" size="16K" attach="rwx" />
			<!-- Test the parsing of the zero attribute -->
			<memsection name="make_dynamically2" size="16K" attach="rwx" zero="false"/>
			<!-- Test the parsing of custom caps. -->
			<memsection name="custom_cap" size="16K" attach="wx">
				<cap name="odd" >
					<right value="read" />
					<right value="execute" />
				</cap>
			</memsection>
			<environment>
				<entry key="Custom" cap="/iguana_server/ig_naming/forward_ref/rw" attach="rw" />
			</environment>
		</pd>
		<program name="ig_naming" file="data/eg_weave/ig_naming" physpool="large">
			<memsection name="forward_ref" size="16K" />
			<environment>
				<entry key="A Key" cap="/iguana_server/the_pd/make_dynamically" attach="rw" />
				<entry key="Custom" cap="/iguana_server/the_pd/custom_cap/odd" attach="wx" />
				<entry key="AVALUE" value="42" />
			</environment>
		</program>
	</iguana>
</image>
